BASE_URL = "https://panel.pro4kings.ro"
MAX_WORKERS = 20
SCAN_INTERVAL = 15  # seconds
OFFLINE_CONFIRM_SECONDS = 30
DATA_RETENTION_DAYS = 30
DB_FILE = "players.db"
USER_AGENT = "P4K-DBS/2.0"
REQUEST_TIMEOUT = 15
